name: README update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install
        
      - name: Update README file
        run: node index.js

      - name: Commit & push README changes
        uses: test-room-7/action-update-file@v2.0.0
        with:
            file-path: README.md
            commit-msg: "chore: updated README.md [skip ci]"
            github-token: ${{ secrets.GITHUB_TOKEN }}